// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrainingManagementSystem.Models;

public partial class CourseEnrollment
{
    public int EnrollmentId { get; set; }

    public int EmployeeId { get; set; }

    public int CourseId { get; set; }

    public int ManagerId { get; set; }

    public string Status { get; set; }

    public string RejectionReason { get; set; }

    public virtual Course Course { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Manager Manager { get; set; }
}